services:
  - type: web
    name: sampleapi
    runtime: docker
    plan: free
    branch: master
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ApiSettings__ApiKey
        generateValue: true
        sync: false
      - key: ASPNETCORE_URLS
        value: http://+:8080

